---
apiVersion: v1
kind: Service
metadata:
  name: external-web
spec:
  ports:
  - port: 6443
    targetPort: 6443 
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-web 
subsets: 
  - addresses:
    - ip: 192.168.23.210 #The IP Address of the external web server
    ports:
    - port: 6443 

